name: Run Open-API Tavern Coverage
on:
  - push # Perform a build of the contents from the branch
  - pull_request # Perform a build after merging with the target branch
  - workflow_dispatch
jobs:
  build_and_release:
    uses: Cray-HPE/open-api-tavern-coverage/.github/workflows/run_open-api-tavern-coverage.yaml@v1
    #the v1 tag exists now
    with:
      open-api-file: "api/swagger.yaml"
      tavern-file-dir: "test/ct/api"
      api-target-urls: "{bss_base_url}"

